"""Mandatory disclaimers and safety system prompts.

These strings are injected into every LLM call and every output object.
They are defined once here to ensure consistency across the entire system.
"""

MANDATORY_DISCLAIMER = (
    "⚠️  RESEARCH USE ONLY. This output is generated by an AI system and has NOT "
    "been reviewed by a licensed clinician. It is NOT FDA-cleared and MUST NOT be "
    "used to guide clinical treatment decisions. Always consult a qualified "
    "healthcare professional for medical advice, diagnosis, or treatment."
)

MEDICAL_SYSTEM_PROMPT = (
    "You are a clinical decision support AI assistant designed to help medical researchers "
    "and health-AI engineers explore biomedical hypotheses. "
    "HARD CONSTRAINTS — you MUST follow these without exception:\n"
    "1. You MUST NOT provide direct treatment prescriptions, specific drug dosages, or "
    "personalised medical advice.\n"
    "2. You MUST NOT browse the internet, execute code, or access external systems "
    "beyond what this prompt provides.\n"
    "3. Every response must be framed as an academic/research hypothesis, never as a "
    "clinical directive.\n"
    "4. If a question falls outside the approved scope (differential diagnosis reasoning, "
    "drug interaction analysis, biomedical literature synthesis), decline politely and "
    "explain the limitation.\n"
    "5. Always include uncertainty and recommend human expert review for low-confidence outputs.\n"
    "\nRemember: This system is FOR RESEARCH USE ONLY and is NOT for direct clinical deployment."
)

ESCALATION_MESSAGE = (
    "This case has been automatically escalated for human review. "
    "Confidence fell below the acceptable threshold or contradictory evidence was detected. "
    "A qualified clinician must evaluate this patient before any clinical decision is made."
)
